import { escapeHtml } from '../../utils/html.js';

export function renderSettings(settings, apiKeys = {}) {
  const actor = settings.actor || {};
  const director = settings.director || {};
  const tavernHint = settings.useTavernApi
    ? '<div class="nai-settings-notice">当前使用酒馆 API：自定义 Endpoint、Key、模型和测试按钮只在关闭该选项后生效。</div>'
    : '<div class="nai-settings-notice">当前使用自定义 API：修改连接信息后可直接点击“拉取模型”或“快速测试”，系统会先保存当前表单。</div>';
  return `<section class="nai-section nai-settings-page"><div class="nai-section-header"><h3><span>⚙️</span>运行与 API 设置</h3></div><div class="nai-section-content"><label class="nai-switch"><input id="nai-enabled" type="checkbox" ${settings.enabled ? 'checked' : ''}> 启用插件总开关</label><label class="nai-switch"><input id="nai-use-tavern" type="checkbox" ${settings.useTavernApi ? 'checked' : ''}> 🍺 使用酒馆 API</label>${tavernHint}<label>并发数 <input id="nai-concurrency" type="number" min="1" max="8" value="${settings.maxConcurrency || 1}"></label><div class="nai-grid-2"><fieldset><legend>🧠 演员/主 AI</legend>${renderApiFields('actor', actor, apiKeys.actor)}</fieldset><fieldset><legend>🎬 导演 AI</legend>${renderApiFields('director', director, apiKeys.director)}</fieldset></div><div class="nai-settings-footer"><span id="nai-settings-status" class="nai-model-status">修改后请保存设置</span><button class="nai-btn nai-btn-primary" data-action="save-settings">💾 保存设置</button></div></div></section>`;
}

function renderApiFields(role, config, apiKey = '') {
  return `<label>提供商 <select data-api="${role}" data-key="provider"><option value="openai" ${config.provider === 'openai' ? 'selected' : ''}>OpenAI 兼容</option><option value="gemini" ${config.provider === 'gemini' ? 'selected' : ''}>Gemini</option><option value="anthropic" ${config.provider === 'anthropic' ? 'selected' : ''}>Anthropic</option></select></label><label>API Key <input type="password" data-api-key="${role}" value="${escapeHtml(apiKey)}" placeholder="随插件设置保存"></label><label>Endpoint <input data-api="${role}" data-key="endpoint" value="${escapeHtml(config.endpoint || '')}"></label><label>模型 <input data-api="${role}" data-key="model" value="${escapeHtml(config.model || '')}" placeholder="手工填写或从下方列表选择"></label><label class="nai-model-select-wrap" data-model-select-wrap="${role}" hidden>可用模型 <select data-model-select="${role}"><option value="">请选择模型</option></select></label><label>Max Tokens <input type="number" min="1" max="200000" data-api="${role}" data-key="maxTokens" value="${config.maxTokens || 32768}"></label><label>超时（毫秒）<input type="number" min="3000" max="600000" data-api="${role}" data-key="timeoutMs" value="${config.timeoutMs || 180000}"></label><label>限流重试次数 <input type="number" min="0" max="6" data-api="${role}" data-key="maxRetries" value="${config.maxRetries ?? 3}"></label><label class="nai-switch"><input type="checkbox" data-api="${role}" data-key="stream" ${config.stream !== false ? 'checked' : ''}> 使用流式响应（失败自动降级）</label><div class="nai-toolbar"><button class="nai-btn" data-action="list-models" data-role="${role}">🔄 拉取模型</button><button class="nai-btn" data-action="test-api" data-role="${role}">⚡ 快速测试</button></div><div class="nai-model-status" data-model-status="${role}">尚未测试</div>`;
}
