import { escapeHtml } from '../../utils/html.js';

export function renderSettings(settings, apiKeys = {}) {
  const actor = settings.actor || {}; const director = settings.director || {};
  return `<section class="nai-section"><label class="nai-switch"><input id="nai-enabled" type="checkbox" ${settings.enabled ? 'checked' : ''}> 启用插件总开关</label><label class="nai-switch"><input id="nai-use-tavern" type="checkbox" ${settings.useTavernApi ? 'checked' : ''}> 🍺 使用酒馆 API</label><label>并发数 <input id="nai-concurrency" type="number" min="1" max="8" value="${settings.maxConcurrency || 1}"></label><div class="nai-grid-2"><fieldset><legend>🧠 演员/主 AI</legend>${renderApiFields('actor', actor, apiKeys.actor)}</fieldset><fieldset><legend>🎬 导演 AI</legend>${renderApiFields('director', director, apiKeys.director)}</fieldset></div><button data-action="save-settings">💾 保存设置</button></section>`;
}

function renderApiFields(role, config, apiKey = '') {
  return `<label>提供商 <select data-api="${role}" data-key="provider"><option value="openai" ${config.provider === 'openai' ? 'selected' : ''}>OpenAI 兼容</option><option value="gemini" ${config.provider === 'gemini' ? 'selected' : ''}>Gemini</option><option value="anthropic" ${config.provider === 'anthropic' ? 'selected' : ''}>Anthropic</option></select></label><label>API Key <input type="password" data-api-key="${role}" value="${escapeHtml(apiKey)}" placeholder="随插件设置保存"></label><label>Endpoint <input data-api="${role}" data-key="endpoint" value="${escapeHtml(config.endpoint || '')}"></label><label>模型 <input data-api="${role}" data-key="model" value="${escapeHtml(config.model || '')}"></label><label>Max Tokens <input type="number" data-api="${role}" data-key="maxTokens" value="${config.maxTokens || 32768}"></label><label>超时（毫秒）<input type="number" min="3000" max="600000" data-api="${role}" data-key="timeoutMs" value="${config.timeoutMs || 180000}"></label><label>限流重试次数 <input type="number" min="0" max="6" data-api="${role}" data-key="maxRetries" value="${config.maxRetries ?? 3}"></label><label class="nai-switch"><input type="checkbox" data-api="${role}" data-key="stream" ${config.stream !== false ? 'checked' : ''}> 使用流式响应（失败自动降级）</label><div class="nai-toolbar"><button data-action="list-models" data-role="${role}">🔄 拉取模型</button><button data-action="test-api" data-role="${role}">⚡ 快速测试</button></div>`;
}
