import { escapeHtml, formatCount } from '../../utils/html.js';
import { renderSection } from './section.js';

export function renderOutline(project = {}, { collapsedSections } = {}) {
  const assets = project.beatAssets || []; const chapters = project.chapters || [];
  const body = chapters.map((chapter) => { const asset = assets.find((item) => item.chapterId === chapter.chapterId); const progress = project.processing?.beats?.[chapter.chapterId]; const status = progress?.status === 'running' ? '🔄 处理中' : progress?.status === 'failed' ? `❌ ${escapeHtml(progress.error || '失败')}` : asset ? '✅ 已生成' : '⏳ 待生成'; return `<article class="nai-outline-card"><button class="nai-outline-toggle" data-action="toggle-outline" data-id="${chapter.chapterId}"><span><strong>${escapeHtml(chapter.chapterName)}</strong><small>${formatCount(chapter.charCount)} 字</small></span><span class="nai-status">${status}　▾</span></button><div class="nai-outline-body" data-outline-body="${chapter.chapterId}">${asset ? `<p>${escapeHtml(asset.summary)}</p><div class="nai-outline-meta">${asset.beats.length} 个节拍 · 开场白 ${asset.opening ? '已生成' : '未生成'}</div><div class="nai-toolbar"><button class="nai-btn nai-btn-small" data-action="view-overview" data-id="${chapter.chapterId}">📖 查看章节概览</button><button class="nai-btn nai-btn-small" data-action="start-chapter" data-id="${chapter.chapterId}">▶ 从这一章开始</button></div>` : '<p class="nai-setting-hint">该章节尚未生成节拍资产。</p>'}<button class="nai-btn nai-btn-small" data-action="reroll-beat" data-id="${chapter.chapterId}">🔄 重 roll 本章</button></div></article>`; }).join('') || '<div class="nai-empty">请先在 TXT 工作台检测章节。</div>';
  return renderSection({ key: 'outline', title: '故事大纲', icon: '🧭', body: `<div class="nai-setting-hint nai-page-intro">按章节查看故事摘要和节拍生成状态；浏览章节不会改变当前故事坐标。</div><div class="nai-outline-list">${body}</div>`, actions: `<button class="nai-btn nai-btn-primary" data-action="parse-beats">🎬 解析节拍</button><button class="nai-btn" data-action="cancel-job">⏹ 取消任务</button>`, collapsedSections });
}

export function renderOverview(project = {}, chapterId, { collapsedSections } = {}) {
  const asset = project.beatAssets?.find((item) => item.chapterId === Number(chapterId)); const stage = project.runtime?.currentStage;
  if (!asset) return renderSection({ key: 'overview', title: '当前章节概览', icon: '🎬', body: '<div class="nai-empty">该章节尚未生成节拍，请先在“故事大纲”中解析。</div>', collapsedSections });
  const chapterOrder = (project.chapters || []).findIndex((chapter) => chapter.chapterId === asset.chapterId); const previous = project.chapters?.[chapterOrder - 1]; const following = project.chapters?.[chapterOrder + 1];
  const beats = asset.beats.map((beat) => { const current = stage?.chapterId === asset.chapterId && stage?.beatId === beat.beatId; return `<article class="nai-beat-card ${current ? 'is-current' : ''}"><div class="nai-beat-header"><strong>${escapeHtml(beat.beatId)}</strong>${current ? '<span class="nai-current-badge">📍 当前位置</span>' : ''}<span class="nai-beat-actions"><button class="nai-icon-btn" data-action="edit-beat" data-id="${escapeHtml(beat.beatId)}">✏️</button><button class="nai-icon-btn" data-action="delete-beat" data-id="${escapeHtml(beat.beatId)}">🗑️</button></span></div><div class="nai-beat-line"><b>📖 事件摘要</b><span>${escapeHtml(beat.summary)}</span></div><div class="nai-beat-line"><b>🎯 退出条件</b><span>${escapeHtml(beat.exitCondition)}</span></div><details><summary>展开节拍原文</summary><pre>${escapeHtml(beat.text)}</pre></details><div class="nai-toolbar"><button class="nai-btn nai-btn-tiny" data-action="merge-beat" data-id="${escapeHtml(beat.beatId)}" data-direction="previous">合并上拍</button><button class="nai-btn nai-btn-tiny" data-action="merge-beat" data-id="${escapeHtml(beat.beatId)}" data-direction="next">合并下拍</button><button class="nai-btn nai-btn-tiny" data-action="move-beat-order" data-id="${escapeHtml(beat.beatId)}" data-direction="-1">↑</button><button class="nai-btn nai-btn-tiny" data-action="move-beat-order" data-id="${escapeHtml(beat.beatId)}" data-direction="1">↓</button></div></article>`; }).join('');
  const toolbar = `<div class="nai-stage-bar"><span>当前故事坐标：<strong>${stage ? `[${stage.chapterId}, ${stage.beatId}]` : '未设置'}</strong></span><div class="nai-toolbar"><button class="nai-btn nai-btn-small" data-action="jump-current-stage">跳转当前坐标</button><button class="nai-btn nai-btn-small" data-action="previous-beat">⏮ 上节拍</button><button class="nai-btn nai-btn-small" data-action="next-beat">⏭ 下节拍</button><button class="nai-btn nai-btn-primary nai-btn-small" data-action="start-chapter" data-id="${asset.chapterId}">从这一章开始</button></div></div>`;
  const body = `${toolbar}<div class="nai-overview-title"><div><small>章节标题</small><h2>${escapeHtml(asset.chapterName)}</h2></div><span class="nai-count-badge">${asset.beats.length} 个节拍</span></div><div class="nai-overview-block"><div class="nai-block-label">故事摘要</div><p>${escapeHtml(asset.summary)}</p><button class="nai-btn nai-btn-small" data-action="edit-story-summary">✏️ 编辑摘要</button></div><div class="nai-overview-block nai-opening"><div class="nai-block-label">开场白（自动提取）</div><p>${escapeHtml(asset.opening || '未生成')}</p></div><div class="nai-block-label">当前小章剧本</div><div class="nai-beat-list">${beats}</div><div class="nai-toolbar nai-chapter-nav"><button class="nai-btn" data-action="view-chapter" data-id="${previous?.chapterId || ''}" ${previous ? '' : 'disabled'}>← 上一章</button><button class="nai-btn" data-action="view-chapter" data-id="${following?.chapterId || ''}" ${following ? '' : 'disabled'}>下一章 →</button></div>`;
  return renderSection({ key: 'overview', title: '当前章节概览', icon: '🎬', body, collapsedSections });
}
