import { escapeHtml } from '../../utils/html.js';

export function renderOutline(project) {
  const assets = project?.beatAssets || []; const chapters = project?.chapters || [];
  return `<section class="nai-section"><div class="nai-toolbar"><button data-action="parse-beats">🎬 解析全部节拍</button><button data-action="cancel-job">⏹ 取消任务</button></div><div class="nai-list">${chapters.map((chapter) => { const asset = assets.find((item) => item.chapterId === chapter.chapterId); const progress = project?.processing?.beats?.[chapter.chapterId]; const status = progress?.status === 'running' ? '🔄 处理中' : progress?.status === 'failed' ? `❌ ${progress.error || '失败'}` : asset ? '✅ 已生成' : '⏳ 待生成'; return `<article class="nai-card"><header><b>${escapeHtml(chapter.chapterName)}</b><span class="nai-status">${status}</span></header>${asset ? `<p>${escapeHtml(asset.summary)}</p><button data-action="view-overview" data-id="${chapter.chapterId}">📖 查看当前章节概览</button><button data-action="start-chapter" data-id="${chapter.chapterId}">▶ 从这一章开始</button>` : ''}<button data-action="reroll-beat" data-id="${chapter.chapterId}">🔄 重roll本章</button></article>`; }).join('') || '<div class="nai-empty">请先捕获章节</div>'}</div></section>`;
}

export function renderOverview(project, chapterId) {
  const asset = project?.beatAssets?.find((item) => item.chapterId === Number(chapterId)); const stage = project?.runtime?.currentStage;
  if (!asset) return '<section class="nai-section"><div class="nai-empty">该章节尚未生成节拍</div></section>';
  const chapterOrder = (project.chapters || []).findIndex((chapter) => chapter.chapterId === asset.chapterId); const previous = project.chapters?.[chapterOrder - 1]; const following = project.chapters?.[chapterOrder + 1];
  return `<section class="nai-section"><div class="nai-toolbar"><b>当前故事坐标：${stage ? `[${stage.chapterId}, ${stage.beatId}]` : '未设置'}</b><button data-action="jump-current-stage">跳转到当前坐标</button><button data-action="previous-beat">⏮ 上节拍</button><button data-action="next-beat">⏭ 下节拍</button><button data-action="start-chapter" data-id="${asset.chapterId}">从这一章开始</button><button data-action="edit-story-summary">✏️ 编辑摘要</button><button data-action="view-chapter" data-id="${previous?.chapterId || ''}" ${previous ? '' : 'disabled'}>上一章</button><button data-action="view-chapter" data-id="${following?.chapterId || ''}" ${following ? '' : 'disabled'}>下一章</button></div><h3>${escapeHtml(asset.chapterName)}</h3><p>节拍数量：${asset.beats.length}</p><p>${escapeHtml(asset.summary)}</p><div class="nai-opening">开场白：${escapeHtml(asset.opening)}</div>${asset.beats.map((beat) => `<article class="nai-card nai-beat ${stage?.chapterId === asset.chapterId && stage?.beatId === beat.beatId ? 'is-current' : ''}"><header><b>${beat.beatId}</b><span>${stage?.chapterId === asset.chapterId && stage?.beatId === beat.beatId ? '📍当前位置' : ''}</span></header><p>📖 ${escapeHtml(beat.summary)}</p><p>🎯 ${escapeHtml(beat.exitCondition)}</p><details><summary>展开节拍原文</summary><pre>${escapeHtml(beat.text)}</pre></details><button data-action="edit-beat" data-id="${escapeHtml(beat.beatId)}">✏️ 编辑</button><button data-action="merge-beat" data-id="${escapeHtml(beat.beatId)}" data-direction="previous">合并上拍</button><button data-action="merge-beat" data-id="${escapeHtml(beat.beatId)}" data-direction="next">合并下拍</button><button data-action="move-beat-order" data-id="${escapeHtml(beat.beatId)}" data-direction="-1">上移</button><button data-action="move-beat-order" data-id="${escapeHtml(beat.beatId)}" data-direction="1">下移</button><button data-action="delete-beat" data-id="${escapeHtml(beat.beatId)}">🗑️ 删除</button></article>`).join('')}</section>`;
}
