import { escapeHtml, formatCount } from '../../utils/html.js';
import { renderWorldbook } from './worldbookView.js';

function section(title, icon, body, actions = '') {
  return `<section class="nai-section"><div class="nai-section-header"><h3><span>${icon}</span>${title}</h3><div class="nai-section-actions">${actions}</div></div><div class="nai-section-content">${body}</div></section>`;
}

export function renderWorkspace(project = {}) {
  const chapters = project.chapters || [];
  const fileBody = `<div class="nai-upload-zone" data-action="choose-file"><div class="nai-upload-icon">📄</div><strong>点击或拖拽 TXT 文件到这里</strong><span>支持 .txt；也可导入本插件工程包 JSON</span><input id="nai-txt-file" type="file" accept=".txt,.json,application/json,text/plain"></div><div class="nai-file-status"><span>${project.sourceText ? `已载入正文 · ${formatCount(project.sourceText.length)} 字` : '尚未载入文件'}</span></div><details class="nai-source-details" ${project.sourceText ? '' : 'open'}><summary>📝 查看/编辑当前正文</summary><textarea id="nai-source-text" rows="10" placeholder="导入 TXT 后正文会显示在这里">${escapeHtml(project.sourceText || '')}</textarea></details>`;
  const cleanBody = `<textarea id="nai-clean-patterns" rows="4" placeholder="输入要删除的重复片段；多个片段用空行分隔"></textarea><div class="nai-toolbar"><button class="nai-btn" data-action="preview-clean">🔍 预览命中</button><button class="nai-btn nai-btn-primary" data-action="apply-clean" disabled>🧹 执行删除</button><button class="nai-btn" data-action="clean-impurities">🧽 删除杂质</button></div><div id="nai-clean-result" class="nai-feedback"></div>`;
  const regexBody = `<div class="nai-setting-hint">按行首识别章节标题，默认规则支持“第一章/第 1 章/卷”等中文章节。</div><input id="nai-chapter-regex" class="nai-input" value="${escapeHtml(project.chapterRegex || '')}" aria-label="章节正则"><div class="nai-toolbar"><button class="nai-btn nai-btn-primary" data-action="capture">🔍 检测章节</button><span class="nai-feedback">${chapters.length ? `已捕获 ${chapters.length} 章，其中 ${chapters.filter((item) => item.confirmed).length} 章已确认` : '尚未检测章节'}</span></div><div id="nai-capture-result" class="nai-feedback"></div>`;
  const queueBody = `<div class="nai-queue-summary"><span>共 ${chapters.length} 章</span><span>${chapters.filter((item) => item.confirmed).length} 章已确认</span><button class="nai-btn nai-btn-danger" data-action="delete-selected-chapters">🗑️ 删除选中</button></div><div class="nai-chapter-queue">${chapters.map((chapter) => `<article class="nai-chapter-card"><div class="nai-chapter-main"><input type="checkbox" data-select-chapter="${chapter.chapterId}"><div class="nai-chapter-title"><strong>${escapeHtml(chapter.chapterName)}</strong><span>${formatCount(chapter.charCount)} 字 · ${chapter.confirmed ? '✅ 已确认' : '⚠️ 待确认'}</span></div></div><div class="nai-chapter-actions"><button class="nai-btn nai-btn-small" data-action="edit-chapter" data-id="${chapter.chapterId}">编辑</button>${chapter.confirmed ? '' : `<button class="nai-btn nai-btn-small" data-action="confirm-chapter" data-id="${chapter.chapterId}">确认</button>`}<button class="nai-btn nai-btn-small" data-action="merge-chapter" data-id="${chapter.chapterId}" data-direction="previous">合并上章</button><button class="nai-btn nai-btn-small" data-action="merge-chapter" data-id="${chapter.chapterId}" data-direction="next">合并下章</button></div></article>`).join('') || '<div class="nai-empty">导入并检测章节后，这里会显示章节队列</div>'}</div>`;
  const fileActions = `<button class="nai-btn nai-btn-small" data-action="import-project">📥 导入工程包</button><button class="nai-btn nai-btn-small" data-action="export-project" ${project.projectId ? '' : 'disabled'}>📤 导出工程包</button>`;
  return `<div class="nai-workspace">${section('文件上传', '📄', fileBody, fileActions)}${section('清洗重复段落', '🧹', cleanBody)}${section('章回正则设置', '📖', regexBody)}${section('章节队列', '📋', queueBody)}${renderWorldbook(project)}</div>`;
}
