import { escapeHtml, tokenEstimate } from '../../utils/html.js';

function renderEntry(entry) {
  return `<article class="nai-entry-card" data-entry-id="${escapeHtml(entry.id)}"><div class="nai-entry-header"><label class="nai-check-label"><input type="checkbox" data-select-entry="${escapeHtml(entry.id)}"><span>📄</span><strong>${escapeHtml(entry.name)}</strong></label><span class="nai-entry-meta">${entry.constant ? '🔵 常驻' : '🟢 触发'} · ${tokenEstimate(entry.content)} tk</span><div class="nai-entry-actions"><button class="nai-icon-btn" title="切换蓝绿灯" data-action="toggle-light" data-id="${escapeHtml(entry.id)}">${entry.constant ? '🟢' : '🔵'}</button><button class="nai-icon-btn" title="设置条目" data-action="edit-entry" data-id="${escapeHtml(entry.id)}">⚙️</button><button class="nai-icon-btn nai-danger" title="删除条目" data-action="delete-entry" data-id="${escapeHtml(entry.id)}">🗑️</button></div></div><button class="nai-entry-toggle" data-action="toggle-entry" data-id="${escapeHtml(entry.id)}">关键词：${escapeHtml((entry.keywords || []).join('、'))} <span>▾</span></button>${entry.expanded ? `<div class="nai-entry-content"><div class="nai-content-label">📝 内容 · ${tokenEstimate(entry.content)} tk</div><textarea data-entry-content="${escapeHtml(entry.id)}" rows="7">${escapeHtml(entry.content)}</textarea></div>` : ''}</article>`;
}

function renderSection(title, icon, body) {
  return `<section class="nai-section"><div class="nai-section-header"><h3><span>${icon}</span>${title}</h3></div><div class="nai-section-content">${body}</div></section>`;
}

export function renderWorldbook(project = {}) {
  const categories = project.categoryConfigs || []; const entries = project.worldbookEntries || [];
  const promptBody = `<div class="nai-prompt-intro">启用至少一个分类后，插件会按章节调用模型抽取条目。点击分类可展开并编辑该分类的提示词。</div><div class="nai-category-stack">${categories.map((category) => `<article class="nai-prompt-card ${category.expanded ? 'is-open' : ''}"><div class="nai-prompt-header"><label class="nai-check-label"><input type="checkbox" data-category-enabled="${escapeHtml(category.id)}" ${category.enabled ? 'checked' : ''}><span>${category.name === '角色' ? '👤' : category.name === '地点' ? '📍' : '🏷️'}</span><strong>${escapeHtml(category.name)}</strong><em>${category.id === 'character' || category.id === 'location' ? '内置' : '自定义'}</em></label><div><button class="nai-icon-btn" data-action="toggle-category" data-id="${escapeHtml(category.id)}">${category.expanded ? '收起' : '展开'}</button><button class="nai-icon-btn" data-action="edit-category" data-id="${escapeHtml(category.id)}">⚙️</button></div></div>${category.expanded ? `<div class="nai-prompt-body"><textarea data-category-prompt="${escapeHtml(category.id)}" rows="8">${escapeHtml(category.prompt || '')}</textarea><div class="nai-setting-hint">允许字段：${escapeHtml((category.fields || []).join('、'))}</div></div>` : ''}</article>`).join('')}</div><button class="nai-btn" data-action="add-category">＋ 自定义分类</button><div class="nai-prompt-footer"><button class="nai-btn nai-btn-primary" data-action="extract-worldbook">📚 提取世界书</button><button class="nai-btn" data-action="cancel-job">⏹ 取消任务</button></div>`;
  const grouped = categories.map((category) => ({ category, entries: entries.filter((entry) => entry.category === category.name) })).filter((group) => group.entries.length);
  const resultBody = `<div class="nai-result-toolbar"><div><strong>已生成 ${entries.length} 个条目</strong><span class="nai-setting-hint"> 可多选后批量处理</span></div><div class="nai-toolbar"><button class="nai-btn" data-action="merge-selected">✋ 手动合并</button><button class="nai-btn" data-action="organize-selected">🧹 整理条目</button><button class="nai-btn nai-btn-danger" data-action="delete-selected-entries">🗑️ 多选删除</button><button class="nai-btn" data-action="export-worldbook">📤 导出世界书</button><button class="nai-btn" data-action="export-card">🎴 导出角色卡</button></div></div><div class="nai-result-groups">${grouped.map((group) => `<section class="nai-result-group"><div class="nai-result-group-header"><strong>${group.category.name}</strong><span>${group.entries.length} 条</span></div>${group.entries.map(renderEntry).join('')}</section>`).join('') || '<div class="nai-empty">尚无生成结果。完成章节捕获后，点击“提取世界书”。</div>'}</div>`;
  return `${renderSection('提取世界书', '📝', promptBody)}${renderSection('生成结果', '📊', resultBody)}`;
}
